CREATE TABLE "USUARIO" (
  "ID_USER" NUMBER(9) NOT NULL,
  "NOME" VARCHAR2(60) NOT NULL,
  "DATA_NASCIMENTO" DATE,
  "GENERO" VARCHAR(20),
  "PREMIUM" NUMBER(1) NOT NULL,
  PRIMARY KEY ("ID_USER")
);

CREATE TABLE "SEGUIDORES" (
  "ID_USER" NUMBER(9) NOT NULL,
  "ID_USER_SEGUINDO" NUMBER(9) NOT NULL,
  PRIMARY KEY ("ID_USER", "ID_USER_SEGUINDO"),
  CONSTRAINT "FK_SEGUIDORES_ID_USER" FOREIGN KEY ("ID_USER") REFERENCES "USUARIO"("ID_USER"),
  CONSTRAINT "FK_SEGUIDORES_USER_SEGUINDO" FOREIGN KEY ("ID_USER_SEGUINDO") REFERENCES "USUARIO"("ID_USER")
);

CREATE TABLE "OUVINTE" (
  "ID_USER" NUMBER(9) NOT NULL,
  "ID_OUVINTE" NUMBER(9) NOT NULL,
  PRIMARY KEY ("ID_OUVINTE")
);

CREATE TABLE "ARTISTA" (
  "ID_USER" NUMBER(9) NOT NULL,
  "ID_ARTISTA" NUMBER(9) NOT NULL,
  "BIO" VARCHAR2(500),
  "AVALIACAO" NUMBER(1),
  PRIMARY KEY ("ID_ARTISTA")
);

CREATE TABLE "ALBUM" (
  "ID_ALBUM" NUMBER(9) NOT NULL,
  "ID_ARTISTA" NUMBER(9) NOT NULL,
  "NOME" VARCHAR2(200) NOT NULL,
  "AVALIACAO" NUMBER(1),
  PRIMARY KEY ("ID_ALBUM"),
  CONSTRAINT "FK_ALBUM.ID_ARTISTA"
    FOREIGN KEY ("ID_ARTISTA")
      REFERENCES "ARTISTA"("ID_ARTISTA")
);

CREATE TABLE "MUSICA" (
  "ID_MUSICA" NUMBER(9) NOT NULL,
  "ID_ALBUM" NUMBER(9) NOT NULL,
  "NOME" VARCHAR2(200),
  "AVALIACAO" NUMBER (1),
  "DURACAO" NUMBER(3) NOT NULL,
  "CURTIDAS" NUMBER(9) NOT NULL,
  PRIMARY KEY ("ID_MUSICA"),
  CONSTRAINT "FK_MUSICA.ID_ALBUM"
    FOREIGN KEY ("ID_ALBUM")
      REFERENCES "ALBUM"("ID_ALBUM")
);
CREATE TABLE "PLAYLIST" (
  "ID_PLAYLIST" NUMBER(9) NOT NULL,
  "ID_OUVINTE" NUMBER(9) NOT NULL,
  "NOME" VARCHAR2(60) NOT NULL,
  PRIMARY KEY ("ID_PLAYLIST"),
  CONSTRAINT "FK_PLAYLIST.ID_OUVINTE"
    FOREIGN KEY ("ID_OUVINTE")
      REFERENCES "OUVINTE"("ID_OUVINTE")
);

CREATE TABLE "LISTADEMUSICAS" (
  "ID_PLAYLIST" NUMBER(9) NOT NULL,
  "ID_MUSICA" NUMBER(9) NOT NULL,
  PRIMARY KEY ("ID_PLAYLIST", "ID_MUSICA"),
  CONSTRAINT "FK_LISTADEMUSICAS.ID_MUSICA"
    FOREIGN KEY ("ID_MUSICA")
      REFERENCES "MUSICA"("ID_MUSICA"),
  CONSTRAINT "FK_LISTADEMUSICAS.ID_PLAYLIST"
    FOREIGN KEY ("ID_PLAYLIST")
      REFERENCES "PLAYLIST"("ID_PLAYLIST")
);

CREATE SEQUENCE seq_id_user
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_id_user_seguindo
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_id_ouvinte
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_id_artista
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_id_album
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_id_playlist
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE seq_id_musica
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
--CRINDO USUARIO 
INSERT INTO USUARIO (ID_USER, NOME, DATA_NASCIMENTO, GENERO, PREMIUM)
VALUES (seq_id_user.nextval, 'Cleber', TO_DATE('30-06-2022', 'dd-mm-yyyy'), 'M', 1)
--CRIANDO OUVINTE
INSERT INTO OUVINTE (ID_USER, ID_OUVINTE)
VALUES (1, seq_id_ouvinte.nextval);

INSERT INTO USUARIO (ID_USER, NOME, DATA_NASCIMENTO, GENERO, PREMIUM)
VALUES (seq_id_user.nextval, 'Rafael', TO_DATE('30-06-2022', 'dd-mm-yyyy'), 'M', 0);
--CRIANDO OUVINTE
INSERT INTO OUVINTE (ID_USER, ID_OUVINTE)
VALUES (2, seq_id_ouvinte.nextval);

INSERT INTO USUARIO (ID_USER, NOME, DATA_NASCIMENTO, GENERO, PREMIUM)
VALUES (seq_id_user.nextval, 'Rodrigo', TO_DATE('30-06-2022', 'dd-mm-yyyy'), 'M', 0);
--CRIANDO OUVINTE
INSERT INTO OUVINTE (ID_USER, ID_OUVINTE)
VALUES (3, seq_id_ouvinte.nextval);

--seguindo
INSERT INTO SEGUIDORES (ID_USER, ID_USER_SEGUINDO)
VALUES (2,1);

INSERT INTO SEGUIDORES (ID_USER, ID_USER_SEGUINDO)
VALUES (1,2);

INSERT INTO SEGUIDORES (ID_USER, ID_USER_SEGUINDO)
VALUES (2,3);

INSERT INTO SEGUIDORES (ID_USER, ID_USER_SEGUINDO)
VALUES (3,1);
INSERT INTO PLAYLIST (ID_PLAYLIST,ID_OUVINTE,NOME)
VALUES (seq_id_playlist.nextval, 1, 'musicas do Cleber sofredor');

INSERT INTO LISTADEMUSICAS (ID_PLAYLIST,ID_MUSICA)
VALUES (1,1);

INSERT INTO LISTADEMUSICAS (ID_PLAYLIST,ID_MUSICA)
VALUES (1,2);

SELECT u.NOME AS Cantora , a.NOME AS Album , m.NOME AS Musica , p.NOME AS Playlist, u2.NOME AS Ouvinte
FROM LISTADEMUSICAS l 
JOIN MUSICA m 
ON m.ID_MUSICA = l.ID_MUSICA
JOIN ALBUM a 
ON a.ID_ALBUM = m.ID_ALBUM 
JOIN ARTISTA a2 
ON a2.ID_ARTISTA = a.ID_ARTISTA 
JOIN USUARIO u 
ON u.ID_USER = a2.ID_USER 
JOIN PLAYLIST p 
ON p.ID_PLAYLIST = l.ID_PLAYLIST
JOIN OUVINTE o 
ON o.ID_OUVINTE = p.ID_OUVINTE 
JOIN USUARIO u2 
ON u2.ID_USER = o.ID_USER;

--artista
INSERT INTO USUARIO (ID_USER, NOME, DATA_NASCIMENTO, GENERO, PREMIUM)
VALUES (seq_id_user.nextval, 'Marisa Monte', TO_DATE('30-06-2022', 'dd-mm-yyyy'), 'M', 1);

INSERT INTO ARTISTA (ID_USER,ID_ARTISTA,BIO,AVALIACAO)
VALUES (4, seq_id_artista.nextval, 'Cantora da nação', 5);

INSERT INTO ALBUM (ID_ALBUM,ID_ARTISTA,NOME,AVALIACAO)
VALUES (seq_id_album.nextval, 1, 'MM', 5);

CREATE SEQUENCE seq_id_musica
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

INSERT INTO MUSICA (ID_MUSICA,ID_ALBUM,NOME,AVALIACAO,DURACAO,CURTIDAS)
VALUES (seq_id_musica.nextval, 1, 'xote de menina', 3, 4, 0);

INSERT INTO MUSICA (ID_MUSICA,ID_ALBUM,NOME,AVALIACAO,DURACAO,CURTIDAS)
VALUES (seq_id_musica.nextval, 1, 'depois', 6, 5, 500);

INSERT INTO MUSICA (ID_MUSICA,ID_ALBUM,NOME,AVALIACAO,DURACAO,CURTIDAS)
VALUES (seq_id_musica.nextval, 1, 'comida', 3, 6, 1000);