--RIGHT OUTER JOIN
SELECT P.NOME, C.NUMERO
	FROM PESSOA p
	RIGHT OUTER JOIN CONTATO c
		ON P.ID_PESSOA = C.ID_PESSOA;

SELECT P.*, EP.* FROM PESSOA p
	RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe  ON P.ID_PESSOA  = PXPE.ID_PESSOA 
	RIGHT OUTER JOIN ENDERECO_PESSOA ep  ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

SELECT P.*, EP.*, C.* FROM PESSOA p
	RIGHT OUTER JOIN CONTATO c
		ON P.ID_PESSOA = C.ID_PESSOA 
	RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe
		ON P.ID_PESSOA  = PXPE.ID_PESSOA 
	RIGHT OUTER JOIN ENDERECO_PESSOA ep
		ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

--FULL OUTER JOIN
SELECT PESSOA.NOME , CONTATO.NUMERO 
	FROM PESSOA 
	FULL OUTER JOIN CONTATO
		ON PESSOA.ID_PESSOA = CONTATO.ID_PESSOA;

SELECT P.*, EP.* FROM PESSOA p
	FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe  ON P.ID_PESSOA  = PXPE.ID_PESSOA 
	FULL OUTER JOIN ENDERECO_PESSOA ep  ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

SELECT P.*, EP.*, C.* FROM PESSOA p
	FULL OUTER JOIN CONTATO c
		ON P.ID_PESSOA = C.ID_PESSOA 
	FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe
		ON P.ID_PESSOA  = PXPE.ID_PESSOA 
	FULL OUTER JOIN ENDERECO_PESSOA ep
		ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;
		
--correção da EXISTS
SELECT p.* 
FROM PESSOA p
WHERE EXISTS(
	SELECT pxpe.ID_PESSOA 
	FROM PESSOA_X_PESSOA_ENDERECO pxpe
	WHERE p.ID_PESSOA = pxpe.ID_PESSOA);

--correção da ULTIMA
SELECT p.ID_PESSOA, p.NOME, ep.ID_ENDERECO, ep.LOGRADOURO
FROM PESSOA_X_PESSOA_ENDERECO pxpe
FULL JOIN PESSOA p
ON p.ID_PESSOA = pxpe.ID_PESSOA
FULL JOIN ENDERECO_PESSOA ep
ON ep.ID_ENDERECO = pxpe.ID_ENDERECO; 






