CREATE TABLE VEM_SER.ESTUDANTE(
id NUMBER NOT NULL,
nome VARCHAR(200) NOT NULL,
data_nascimento DATE NOT NULL,
nr_matricula NUMBER(10) UNIQUE NOT NULL,
ativo CHAR(1), --S ativo e N naoAtivo
PRIMARY KEY (id)
);


CREATE SEQUENCE seq_estudante
 START WITH     100
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
INSERT INTO VEM_SER.ESTUDANTE(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA , ATIVO) VALUES(SEQ_ESTUDANTE.nextval, 'Rafael', '29-JAN-1982',1001, 'S');
INSERT INTO VEM_SER.ESTUDANTE(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA , ATIVO) VALUES(SEQ_ESTUDANTE.nextval, 'Samuel', '24-SEP-2012', 1002, 'S');
INSERT INTO VEM_SER.ESTUDANTE(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA , ATIVO) VALUES(SEQ_ESTUDANTE.nextval, 'Alice', '26-MAY-2016', 1003, 'S');
INSERT INTO VEM_SER.ESTUDANTE(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA , ATIVO) VALUES(SEQ_ESTUDANTE.nextval, 'Mateus', '22-MAR-2018', 1004,'S');
INSERT INTO VEM_SER.ESTUDANTE(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA , ATIVO) VALUES(SEQ_ESTUDANTE.nextval, 'Tasia', '30-AUG-1982', 1005,'S');
INSERT INTO VEM_SER.ESTUDANTE(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA , ATIVO) VALUES(SEQ_ESTUDANTE.nextval, 'Gabriel', '09-JUL-1986', 1006,'S');
INSERT INTO VEM_SER.ESTUDANTE(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA , ATIVO) VALUES(SEQ_ESTUDANTE.nextval, 'Daniel', '12-JAN-1984', 1007,'S');
INSERT INTO VEM_SER.ESTUDANTE(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA , ATIVO) VALUES(SEQ_ESTUDANTE.nextval, 'Jorge', '01-APR-2000', 1008,'N');
INSERT INTO VEM_SER.ESTUDANTE(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA , ATIVO) VALUES(SEQ_ESTUDANTE.nextval, 'Marcio', '30-DEC-1994', 1009,'N');
INSERT INTO VEM_SER.ESTUDANTE(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA , ATIVO) VALUES(SEQ_ESTUDANTE.nextval, 'Lucas', '20-OCT-2006', 1010,'N');

SELECT * FROM VEM_SER.ESTUDANTE;
