-- exercicio 1 Aula 3
UPDATE ENDERECO
	SET LOGRADOURO = '***NAO SEI ***'
	WHERE ID_ENDERECO = 2;
UPDATE ENDERECO
	SET COMPLEMENTO = '****NAO SEI MESMO******'
	WHERE ID_ENDERECO  = 3;


UPDATE ENDERECO
SET NUMERO = 9999999
WHERE ID_ENDERECO = 4;

DELETE ENDERECO
WHERE (SELECT MAX(ID_ENDERECO)
FROM ENDERECO);

DELETE ENDERECO
WHERE NUMERO = 999999;

DELETE ENDERECO
WHERE ID_ENDERECO = 2 AND ID_ENDERECO = 3;