SELECT PESSOA.NOME , CONTATO.NUMERO 
FROM PESSOA CROSS JOIN CONTATO ;

--INNER JOIN
SELECT PESSOA.NOME , CONTATO.NUMERO 
FROM PESSOA INNER JOIN CONTATO ON PESSOA.ID_PESSOA = CONTATO.ID_PESSOA ;

SELECT * FROM PESSOA
INNER JOIN PESSOA_X_PESSOA_ENDERECO pxpe  ON PESSOA.ID_PESSOA  = PXPE.ID_PESSOA 
INNER JOIN ENDERECO_PESSOA ep  ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

SELECT * FROM PESSOA
INNER JOIN CONTATO ON PESSOA.ID_PESSOA = CONTATO.ID_PESSOA 
INNER JOIN PESSOA_X_PESSOA_ENDERECO pxpe  ON PESSOA.ID_PESSOA  = PXPE.ID_PESSOA 
INNER JOIN ENDERECO_PESSOA ep  ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

--LEFT JOIN
SELECT PESSOA.NOME , CONTATO.NUMERO 
FROM PESSOA 
LEFT OUTER JOIN CONTATO
ON PESSOA.ID_PESSOA = CONTATO.ID_PESSOA ;

SELECT * FROM PESSOA
LEFT JOIN PESSOA_X_PESSOA_ENDERECO pxpe  ON PESSOA.ID_PESSOA  = PXPE.ID_PESSOA 
LEFT JOIN ENDERECO_PESSOA ep  ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

SELECT * FROM PESSOA
LEFT JOIN CONTATO ON PESSOA.ID_PESSOA = CONTATO.ID_PESSOA 
LEFT JOIN PESSOA_X_PESSOA_ENDERECO pxpe  ON PESSOA.ID_PESSOA  = PXPE.ID_PESSOA 
LEFT JOIN ENDERECO_PESSOA ep  ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;